# DRAFT_MODEL_PATH = "mad1999/pho-whisper-tiny-ct2"
# VERIFY_MODEL_PATH = "mad1999/pho-whisper-large-ct2"

DRAFT_MODEL_PATH = "tiny"
VERIFY_MODEL_PATH = "large-v3"

# Cấu hình âm thanh
SAMPLE_RATE = 16000
CHUNK_DURATION_MS = 30
CHUNK_SIZE = int(SAMPLE_RATE * CHUNK_DURATION_MS / 1000)

# Cấu hình VAD
WEBRTC_SENSITIVITY = 3
SILENCE_THRESHOLD_MS = 800
SILERO_CONFIDENCE_THRESHOLD = 0.5

# Cấu hình UI
MAX_SENTENCES = 3